version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.10.0

      steps:
        - checkout

        - run:
            name: teste
            command: npm -v


  test:
    docker:


      # specify the version you desire here
      - image: circleci/openjdk:8-jdk


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
workflows:
#  main:
#    jobs:
#      - build:
#          context: SonarCloud
  version: 2
  build_and_test:
    jobs:
      - build:
          context: SonarCloud
      - test